version: "3"
services:
  rabbitmq:
    image: rabbitmq:4
    env_file: secrets/environment.env
    volumes:
      - C:/var/lib/rabbitmq:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - defaultnetwork
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
  
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    shm_size: 128mb
    env_file: secrets/environment.env
    volumes:
      - C:/var/lib/postgresql:/var/lib/postgresql
    networks:
      - defaultnetwork
  
  observer:
    build:
      context: "."
      dockerfile: "Observer.App/Dockerfile"
    env_file: secrets/environment.env
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
    networks:
      - defaultnetwork
  
  notifier:
    build:
      context: "."
      dockerfile: "Notifier.App/Dockerfile"
    env_file: secrets/environment.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - defaultnetwork

networks:
  defaultnetwork:
    driver: bridge